#-----------------------------------
#- Placeholders:
# %prefix%
# %suffix%
# %prefixes%
# %suffixes%
# %world%
# %username%
# %displayname%
# %username-color%  | tip: add meta to user or group "meta.username-color.&<colorCode>"
# %message-color%   | tip: add meta to user or group "meta.message-color.&<colorCode>"
# %chatmessage%
#-----------------------------------
#
#- Color Codes:
# &0 - Black      | &1 - Dark Blue
# &2 - Dark Green | &3 - Dark Aqua
# &4 - Dark Red   | &5 - Dark Purple
# &6 - Gold       | &7 - Gray
# &8 - Dark Gray  | &9 - Blue
# &a - Green      | &b - Aqua
# &c - Red        | &d - Light Purple
# &e - Yellow     | &f - White
#-----------------------------------
# &k - Random Symbols | &l - Bold
# &m - Strikethrough  | &n - Underline
# &o - Italic         | &r - Reset
#-----------------------------------
#
#
#Chat format string with placeholders.
chatFormat = "%prefix% %suffix% &2%username%&f: %chatmessage%"
